version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.4-jdk
    steps:
      - checkout
      - run: mvn clean verify
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - build
